# Targets used by all java projects.

java_plugin(
    name = "auto_value_plugin",
    processor_class = "com.google.auto.value.processor.AutoValueProcessor",
    deps = [
        "@tzbits_maven//:com_google_auto_value_auto_value",
        "@tzbits_maven//:com_google_auto_value_auto_value_annotations",
    ],
    visibility = ["//visibility:public"],
)