java_test(
    name = "TranspilerTest",
    srcs = ["TranspilerTest.java"],
    deps = [
        "//java/com/tzbits/ninelives",
        "//third_party:junit",
        "//third_party:truth",
    ]
)

java_test(
    name = "JsExprTest",
    srcs = ["JsExprTest.java"],
    deps = [
        "//java/com/tzbits/ninelives",
        "//third_party:junit",
        "//third_party:truth",
    ]
)
