load("@rules_java//java:defs.bzl", "java_test")

java_test(
    name = "TranspilerTest",
    srcs = ["TranspilerTest.java"],
    deps = [
        "//java/com/tzbits/ninelives",
        "//third_party:junit",
        "//third_party:truth",
    ],
)
